### ISSUE TITLE
Error when running demo_img.py

### ISSUE THREAD

**Issue by Tetsujinfr** [nqanh/affordance-net#1]
hi
thanks for your code.
So after compiling etc, I just reach the magic moment of running your demo_img.py

But then, after crunching about 30 seconds (or a bit more), I have the following errors:

```
~/affordance-net$ ./tools/demo_img.py
./tools/demo_img.py: line 4: $'\nSee README.md for installation instructions before running.\nDemo script to perform affordace detection from images\n': command not found
from: can't read /var/mail/fast_rcnn.config
from: can't read /var/mail/fast_rcnn.test
from: can't read /var/mail/fast_rcnn.nms_wrapper
from: can't read /var/mail/utils.timer
./tools/demo_img.py: line 19: CONF_THRESHOLD: command not found
./tools/demo_img.py: line 20: good_range: command not found
./tools/demo_img.py: line 23: syntax error near unexpected token `('
./tools/demo_img.py: line 23: `cwd = os.getcwd()'
```
Any help would be much appreciated. Thanks a lot

Tets

**Comment by nqanh** [comment]
Thanks for the feedback! I made a mistake in the readme file (sorry about that). To run the demo, after the installation, just do this:
- cd to the `tools` folder: `cd $AffordanceNet_ROOT/tools`
- run the python script when you're **inside** the `tools` folder: `python demo_img.py`

Please see the updated Readme for details.

**Comment by Tetsujinfr** [comment]
Ok thanks, that did the trick :)

I have a few issues with memory and low detection confidence but I will post under a separate issue since I can now run the demo.

before I close this issue, do you save the result of the outputs somewhere or I need to tweak the code to output the opencv window as an image somewhere?

I see a "temp_output" folder under tools/ but it seems not used at all.

Tets

**Comment by Tetsujinfr** [comment]
Ok I did uncmment the code lines in demo.py which are saving down the results, useful.

![obj_detction](https://user-images.githubusercontent.com/29961693/31265519-1926016a-aa67-11e7-8406-7d41047d8871.jpg)

![mask0](https://user-images.githubusercontent.com/29961693/31265523-1f553cfe-aa67-11e7-9c30-7064253aba6d.jpg)

I close this, thanks.
Tets
