### ISSUE TITLE
Regarding cudnn version and caffe installation

### ISSUE THREAD

**Issue by Cheren15** [nqanh/affordance-net#32]
@nqanh 
Hi, 
Do I need to install official caffe or just install your modified version, I have some compiling problem with your cudnn_tanh_layer, so I want to double check that you are using CUDA8.0 and cudnn5, not 5.1?

**Comment by nqanh** [comment]
You need to build and install caffe version from this repo. Any recent cuda/cudnn version should be fine.
Best,

**Comment by Cheren15** [comment]
Ok, Thank you for your reply, and when I am  running training codes, some thing wrong as follow:

Logging output to experiments/logs/faster_rcnn_end2end_VGG16_.txt.2018-07-02_17-50-31
+ ./tools/train_net.py --gpu 1 --solver models/pascal_voc/VGG16/faster_rcnn_end2end/solver.prototxt --weights data/imagenet_models/VGG16.v2.caffemodel --imdb voc_2012_train --iters 2000000 --cfg experiments/cfgs/faster_rcnn_end2end.yml
./experiments/scripts/faster_rcnn_end2end.sh: line 59: ./tools/train_net.py: Permission denied

And I used sudo bash ./experiments/scripts/faster_rcnn_end2end.sh 0 VGG16 pascal_voc
It still has same problem, do you have any suggestion on this?

**Comment by Cheren15** [comment]
I have tried chmod the *.sh and train_net.py file, now I got a new error:

Logging output to experiments/logs/faster_rcnn_end2end_VGG16_.txt.2018-07-02_20-43-52
+ ./tools/train_net.py --gpu -1 --solver models/pascal_voc/VGG16/faster_rcnn_end2end/solver.prototxt --weights data/imagenet_models/VGG16.v2.caffemodel --imdb voc_2012_train --iters 2000000 --cfg experiments/cfgs/faster_rcnn_end2end.yml
Traceback (most recent call last):
  File "./tools/train_net.py", line 13, in <module>
    from fast_rcnn.train import get_training_roidb, train_net
  File "/home/chen/DL/affordance-net/tools/../lib/fast_rcnn/train.py", line 10, in <module>
    import caffe
ImportError: No module named caffe

However, I could import caffe via python with command line and I am sure I have make the pycaffe.

**Comment by Cheren15** [comment]
@nqanh

**Comment by Cheren15** [comment]
I just fixed several problems, for the first chmod +x *.sh and *.py files mention in error report. and the second one is the problem of env variables setting, now I move on to the next data preparing stage, It  just like what you said it should be ok for current CUDA 9.2.88. Thanks again, I will close this issue.
